name: CI/CD pipelin
env:
  EB_PACKAGE_S3_BUCKET_NAME : "spring-securuti-mvs"
  EB_APPLICATION_NAME       : "spring-security-mvs"
  EB_ENVIRONMENT_NAME       : "Springsecuritymvs-env"
  DEPLOY_PACKAGE_NAME       : "mvs_test_${{ github.sha }}.xml"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
      - uses: actions/checkout@v1
      
      - name: setup up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 1.17
          
      - name: Maven Package
        run: mvn -B clean package --$ {{ env.DEPLOY_PACKAGE_NAME }}
        
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
         aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }} 
         aws-region            : ${{ env.AWS_REGION_NAME }}
         
      - name: Copy Deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
       
      - name: Priny Happy Message for CI finish
        run : echo "CI Pileline part finished successfully!"
